version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "127.0.0.1:27019:27017"  # Bind to localhost on the host machine
    volumes:
      - ./mongo-data:/data/db  # Mount a local volume for MongoDB data persistence
